##### Task 4

### a) 

Since $B(t)$ is a $C^1$ function we know that it has to be continious and continious differentiable in the interval $t \in [0, m]$. In other words $B(t)$ has to satisfy the following conditions

$$
\begin{cases}
p_{3,i} = p_{0,i+1}, & \forall \; i = 1, \ldots, m-1 \\
p_{3,i} - p_{2,i} = p_{1,i+1} - p_{0,i+1},  & \forall \; i = 1, \ldots, m-1.
\end{cases}
$$

From the equation above we observe that $p_{2,i}$ can be expressed as

$$
p_{2,i} = 2p_{0,i+1} - p_{1,i+1}
$$

We can try and phrase this information using the velocity $v_{i+1}$ at $p_{0,i+1}$. Using the results from $\textbf{2c)}$ and the equation above we get that

$$
\begin{align*}
v_{i+1} &= c_{i+1}'(0) \\
&= 3 (p_{1,i+1}-p_{0,i+1}) \\
&= 3 \left(p_{1,i+1} - \frac{1}{2}(p_{2,i} +  p_{1,i+1})\right) \\
&= \frac{3}{2}\left(p_{1,i+1} - p_{2,i}\right)
\end{align*}
$$

We observe that from this expression we can recover both “neighboring” points $p_{2,i}$ and $p_{1,i+1}$.


### b) 

We want to minimize the (squared) acceleration of the curve

$$
F(\mathbf{P}) := \int_0^m ||\mathbf{B}''(t)||^2 dt,
$$

with respect to the remaining control points 

$$
\mathbf{P} = [p_{0,1},p_{1,1}, p_{0,2}, p_{1,2}, \ldots , p_{0,m-1}, p_{1,m-1}, p_{0,m}, p_{1,m}, p_{2,m}, p_{3,m}].
$$

For simplicity we only consider one segment of the composite Bézier curve for the points ($q_0$, $q_1$, $q_2$, $q_3$) $\in \mathbb{R}^2$; $b_3(t; q_0, q_1, q_2, q_3)$ and use this to find the gradient of 

$$
\tilde{F}(q_0,q_1,q_2,q_3) := \int_0^1 ||b_3''(t;q_0, q_1, q_2, q_3)||_2^2 dt
$$

with respect to the control points $q_i$, $i = 0, \ldots, 3$. From task $\textbf{2c)}$ we recall that

$$
\begin{align*}
b_3''(t;q_0, q_1, q_2, q_3) &= 3 \cdot 2 \left[ \sum_{i=0}^{3-2} B_{i,3-2}(t)\left(q_{i+2} - 2q_{i+1} + q_{i}\right) \right] \\
&= 6 \left[ \sum_{i=0}^{1} B_{i,1}(t)\left(q_{i+2} - 2q_{i+1} + q_{i}\right) \right] \\
&= 6 \left[ B_{0,1}(t)(q_2 -2q_1 + q_0) + B_{1,1}(t)(q_3 -2q_2 + q_1)\right] \\
&= 6 \left[ \binom{1}{0}t^{0}(1-t)^{1-0}(q_2 -2q_1 + q_0) + \binom{1}{1}t^{1}(1-t)^{1-1}(q_3 -2q_2 + q_1)\right] \\
&= 6 \left[ (1-t)(q_2 - 2q_1 + q_0) + t(q_3 - 2q_2 + q_1)\right] \\
&= 6 \left[ t(q_3 -3q_2 + 3q_1 - q_0) + q_2 -2q_1 + q_0 \right] 
\end{align*}
$$

Thus

$$
\begin{align*}
\tilde{F}(q_0,q_1,q_2,q_3) &:= \int_0^1 ||b_3''(t;q_0, q_1, q_2, q_3)||_2^2 dt \\
&= \int_0^1 ||6 \left[ t(q_3 -3q_2 + 3q_1 - q_0) + q_2 -2q_1 + q_0 \right] ||_2^2 dt \\
&= 36 \int_0^1 \left(t(q_3 -3q_2 + 3q_1 - q_0)+q_2 -2q_1 + q_0\right)^2 dt \\,
\end{align*}
$$
we let $p = (q_3 -3q_2 + 3q_1 - q_0)$ and $r = (q_2 -2q_1 + q_0)$ and we obtain 

$$
\begin{align*}
\tilde{F}(q_0,q_1,q_2,q_3) &:= 36 \int_0^1 \left(tp + r \right)^2 dt \\
&= 36 \int_0^1 t^2 p^2+ 2tpr + r^2 dt \\
&= 36 \left[\frac{1}{3} p^2 t^3 + prt^2  +r^2t\right]_0^1 \\
&= 36 \left(\frac{1}{3} p^2 + pr  +r^2\right) \\
&= 36 \left(\frac{1}{3} (q_3 -3q_2 + 3q_1 - q_0)^2 + (q_3 -3q_2 + 3q_1 - q_0)(q_2 -2q_1 + q_0) + (q_2 -2q_1 + q_0)^2 \right)\\
&= 12\left( q_0^2-3q_1q_0 + q_3q_0 + 3q_1^2+3q_2^2+q_3^2-3q_1q_2-3q_2q_3 \right),
\end{align*}
$$

and the gradient of $\tilde{F}(q_0,q_1,q_2,q_3)$ is given by

$$
\begin{align*}
\nabla \tilde{F}(q_0,q_1,q_2,q_3) &= \left( \frac{\partial \tilde{F}}{\partial q_0}, \frac{\partial \tilde{F}}{\partial q_1}, \frac{\partial \tilde{F}}{\partial q_2}, \frac{\partial \tilde{F}}{\partial q_3}\right) \\
&= 12\left([2q_0-3q_1+q_3], [-3q_0+6q_1-3q_2], [-3q_1+6q_2-3q_3], [q_0 -3q_2+2q_3]\right) \\
&= 12\begin{bmatrix} 
2 & -3 & 0 & 1 \\
-3 & 6 & -3 & 0 \\
0 & -3 & 6 & -3 \\
1 & 0 & -3 & 2
\end{bmatrix}
\begin{bmatrix} q_0 \\ q_1 \\ q_2 \\ q3 \end{bmatrix}
\end{align*}
$$

We can use this result to compute the whole gradient of $F$ based on the compressed $\mathbf{P} = [p_{0,1},p_{1,1},p_{0,2}, p_{1,2}, \ldots , p_{0,m-1}, p_{1,m-1}, p_{0,m}, p_{1,m},p_{2,m}, p_{3,m}]$. From task $\textbf{4a)}$ we know that the missing points in sequence $c_i$ for $i= 1,\ldots, m-1$ can be expressed using the first two points in the next sequence. We obtain that $\tilde{F}_i(p_{0,i}, p_{1,i},p_{2,i}, p_{3,i}) = \tilde{F}_i(p_{0,i}, p_{1,i},2p_{0,i+1}-p_{1,i+1}, p_{0,i+1})$. Using this and the linearity of the $\nabla$ operator we get that



$$
\begin{align*}
\nabla F(p_{0,1}, p_{1,1}, \ldots, p_{3,m}) &= \left( \frac{\partial F}{\partial p_{0,1}}, \frac{\partial F}{\partial p_{1,1}}, \ldots, \frac{\partial F}{\partial p_{3,m}} \right) \\
&= \left( \frac{\partial \tilde{F_1}}{\partial p_{0,1}}, \frac{\partial \tilde{F_1}}{\partial p_{1,1}}, \ldots, \frac{\partial \tilde{F_m}}{\partial p_{3,m}} \right)
\end{align*}
$$



Task: 
While we do not want to write down the whole gradient of F, sketch how you can
use the result of F˜ to compute the gradient of F. Remember that B(t) is continuously
differentiable.


### c) 
We try to solve the equation 

$$
\nabla \tilde{F}(\mathbf{q}^*) = 0
$$

then $\mathbf{q}^*$ is a possible minimizer for $\tilde{F}(\mathbf{q})$. We use our calculated gradient from $\textbf{4b)}$ and we get that

$$
\nabla \tilde{F}(\mathbf{q^*}) = 12\begin{bmatrix} 
2 & -3 & 0 & 1 \\
-3 & 6 & -3 & 0 \\
0 & -3 & 6 & -3 \\
1 & 0 & -3 & 2
\end{bmatrix}
\begin{bmatrix}
q^*_0 \\ q^*_1 \\ q^*_2 \\ q^*_3
\end{bmatrix}
= \vec{0}
$$

We reduce the matrix to row echolon form and obtain 

$$
\begin{bmatrix}
1 & 0 & -3 & 2\\
0 & 1 & -2 & 1 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{bmatrix}
\begin{bmatrix}
q^*_0 \\ q^*_1 \\ q^*_2 \\ q^*_3
\end{bmatrix}
= \vec{0}
$$

From the row echolon representation above we observe that $q^*_2$ and $q^*_3$ are free variables. Which means that the solution to the equation $\nabla \tilde{F}(\mathbf{q}^*) = 0$ has infinitly many solutions. We let $q^*_2 = r$ and $q^*_3 = s$ for any points $r,s \in \mathbb{R}^2$. Then the solution of  $\tilde{F}(\mathbf{q}^*) = 0$ is 

$$
\mathbf{q}^* = \begin{bmatrix}q^*_0 \\ q^*_1 \\ q^*_2 \\ q^*_3\end{bmatrix} = \begin{bmatrix} 3r - 2s \\ 2r -s \\ r \\ s \end{bmatrix}
$$

We observe from task $\textbf{4b)}$ that $\tilde{F}(\mathbf{q}) \geq 0$ for all $\mathbf{q}$. We want to check if our $\mathbf{q}^*$ is actually a minimizer for $\tilde{F}(\mathbf{q})$ and obtain:

$$
\begin{align*}
&\tilde{F}(3r-2s,2r-s,r,s) \\
&= 36 \left(\frac{1}{3} (s -3r + 3(2r-s) - (3r-2s))^2 + (s -3r + 3(2r-s)- (3r-2s))(r -2(2r-s) + (3r-2s)) + (r -2(2r-s) + (3r-2s))^2 \right)\\
&= 36 \left(\frac{1}{3} (s-3s+2s -3r+6r-3r)^2 + (s-3s+2s -3r+6r-3r)(2s-2s + r-4r+3r) + (2s-2s +r-4r+3r)^2 \right)\\
&= 36 \left( 0 + 0\cdot 0 + 0 \right) \\
&= 0
\end{align*}
$$

We observe from the result above that our $\mathbf{q}^*$ is a global minimizer for the function $\tilde{F}(q_0,q_1,q_2,q_3)$, since 

$$
\begin{align*}
\tilde{F}(\mathbf{q}^*) \leq \tilde{F}(\mathbf{q}), &&\forall \mathbf{q}.
\end{align*}
$$

For the overall problem $F$ we have to take into account the properties of $C^1$ between the segments. For simplicity 

Task: 
For the overall problem F we even have to take into account the properties from the C^1
property between the segments. What about the solution now? Is it unique? You may
argue intuitively here or provide a concrete example of two minimisers for a 2-segment
curve, i.e. m = 2.


### d)

We extend our problem to have some (data) points $\mathbf{d}_i \in \mathbb{R}^2$, $i = 0,\ldots m$ and we extend the problem to

$$
G_{\lambda}(\mathbf{P}) = \frac{\lambda}{2} \sum_{i=0}^{m} ||\mathbf{d}_i - \mathbf{B}(i)||_2^2 + \int_0^m ||\mathbf{B}''(t)||_2^2 dt,
$$

for some $\lambda > 0$. Again we want to look at the simple case when we only have two points $s,e \in \mathbb{R}^2$ and we get that

$$
\begin{align*}
\tilde{G}_{\lambda}(q_0,q_1,q_2,q_3) &= \frac{\lambda}{2} \left(||s - b_3(0;q_0,q_1,q_2,q_3)||_2^2 + ||e - b_3(1;q_0,q_1,q_2,q_3)||_2^2\right) + \tilde{F}(q_0,q_1,q_2,q_3) \\
&= \frac{\lambda}{2} \left(||s - q_0||_2^2 + ||e - q_3||_2^2\right) + \tilde{F}(q_0,q_1,q_2,q_3) 
\end{align*}
$$

We recall that $\tilde{F}(q_0,q_1,q_2,q_3)$ is given by

$$
\tilde{F}(q_0,q_1,q_2,q_3) = 36 \left[ |q_3 -3q_2 + 3q_1 - q_0|^2 + |q_2 -2q_1 + q_0|^2 \right],
$$

and that $\nabla \tilde{F}(\mathbf{q}^*) = 0$ had the solution 

$$
\mathbf{q}_\tilde{F}^* = \begin{bmatrix}q^*_0 \\ q^*_1 \\ q^*_2 \\ q^*_3\end{bmatrix} = \begin{bmatrix} 3a - 2b \\ 2a -b \\ a \\ b \end{bmatrix},
$$

for any points $a,b \in \mathbb{R}^2$.
Now we will find a minimizer for $\tilde{G}_{\lambda}(q_0,q_1,q_2,q_3)$ and determine if this minimizer is unique. We directly see from the equations that $\tilde{G}_{\lambda}(q_0,q_1,q_2,q_3)$  has its global minima when $s = q_0$, $e = q_3$ and $\mathbf{q} = \mathbf{q}^*_{\tilde{F}}$. Thus we get that 

$$
\mathbf{q}^*_{G_{\lambda}}= \begin{bmatrix} 3a - 2b \\ 2a -b \\ a \\ b \end{bmatrix} = \begin{bmatrix} s \\ 2a -b \\ a \\ e\end{bmatrix} 
\Rightarrow \begin{cases} q_0 = s = 3a -2b \\ q_1 = 2a -b \\ q_2 = a \\ q_3 = e = b \end{cases}
\Rightarrow \begin{cases} a = \frac{1}{3}(s+ 2e) \\ b= e \end{cases}, 
$$

and we obtain the unique minimizer 

$$
\mathbf{q}^*_{G_{\lambda}} = \begin{bmatrix} s \\ \frac{2}{3}(s + 2e) - e \\ \frac{1}{3}(s+ 2e) \\ e \end{bmatrix} = 
\begin{bmatrix} s \\ \frac{1}{3}(2s + e) \\ \frac{1}{3}(s + 2e) \\ e \end{bmatrix} 
$$

If we let $\lambda$ tend to zero in this model we ignore the first term of the equation and we get 

$$
\tilde{G}_{\lambda}(q_0,q_1,q_2,q_3) = \tilde{F}(q_0,q_1,q_2,q_3), 
$$

and we loose the uniqueness since $\tilde{F}(q_0,q_1,q_2,q_3)$ has not unique minimizer. When $\lambda$ tend to $\infty$ we get 

$$
\tilde{G}_{\lambda}(q_0,q_1,q_2,q_3) = \lim_{\lambda\to\infty} \frac{\lambda}{2} \left(||s - q_0||_2^2 + ||e - q_3||_2^2\right) + \tilde{F}(q_0,q_1,q_2,q_3) , 
$$

and we observe that the equation has its global minima when $\mathbf{q} = \mathbf{q}^*_{G_{\lambda}}$. We also observe that if $s \neq q_0$ or $e \neq q_3$  $\tilde{G}_{\lambda}(q_0,q_1,q_2,q_3)$ also tends to $\infty$ as $\lambda \to \infty$. 

For the bigger problem $G_{\lambda}(\mathbf{P})$ for $m+1$ (data) points we also have uniqueness. This can be shown by induction. 

$\textbf{Proof}$: When we have two points we have allready shown that this results in a unique minimizer. For each point $\mathbf{d}_i$ we add, we get another unique minimizer for the added sequence. Thus for $m+1$ points $\mathbf{d}_i$ for $i = 0, \ldots, m$ we have $m$ subsequences $\tilde{G}_{\lambda}(q_0,q_1,q_2,q_3)$ from $\mathbf{d}_i \to \mathbf{d}_{i+1}$, $i = 0,\ldots, m-1$ each with a unique solution. Since $G_{\lambda}(\mathbf{P})$ can be written as a linear combination of subsequences $\tilde{G}_{\lambda}(q_0,q_1,q_2,q_3)$ with unique minimizers, $G_{\lambda}(\mathbf{P})$ also need to have a unique minimizer.

If we let $\lambda \to 0$ we loose the uniqueness of the minimizer since $G_{0}(\mathbf{P}) : = F(\mathbf{P})$ which do not have a unique minimizer. When $\lambda \to \infty$  we still have a unique minimizer for $G_{\lambda}(\mathbf{P})$. But if some of the (data) points $\mathbf{d}_i \neq p_{0,i+1}$ for $i = 0, \ldots, m-1$ or $\mathbf{d}_m \neq p_{3,m}$, then $G_{\lambda}(\mathbf{P})$ also tends to $\infty$.

### e) 

Now we want to find a gradient descent method to minimize our function $G_{\lambda}(\mathbf{P})$ where we use the $\mathbf{P}$ from task $\textbf{3)}$.


In [56]:
import numpy as np

# Takes parameters:
# 𝜆: parameter for G
# P: remaining data points
P = np.array([[-1, 0], [-1, 1 / 3], [0, 1], [1 / 3, 1], [1, 0], [1, -1 / 3], [1 / 3, -1], [0, -1]])  

def gradient_F_tilde(q):
    return 12*np.array([2*q[0]-3*q[1]+q[3], -3*q[0]+6*q[1]-3*q[2], -3*q[1]+6*q[2]-3*q[3], q[0] -3*q[2]+2*q[3]])

def compress_P(P_full):
    c_P = []
    for i in range(0, len(P_full)-4, 4):
        c_P.append(P_full[i])
        c_P.append(P_full[i+1])
    c_P.append(P_full[-4])
    c_P.append(P_full[-3])
    c_P.append(P_full[-2])
    c_P.append(P_full[-1])
    return np.array(c_P)


def gradient_F(P):
    gradient = np.zeros_like(P)
    for i in range(0, len(P)-4,2):
        g_F_tilde = gradient_F_tilde(np.array([P[i],P[i+1],2*P[i+2]-P[i+3], P[i+2]]))
        gradient[i] = g_F_tilde[0]
        gradient[i+1] = g_F_tilde[1]
    g_F_tilde = gradient_F_tilde(np.array([P[-4],P[-3],P[-2], P[-1]]))
    gradient[-4],gradient[-3], gradient[-2], gradient[-1]  = g_F_tilde[0], g_F_tilde[1], g_F_tilde[2], g_F_tilde[3]
    return gradient


def gradient_G(D,P,𝜆): 
    gradient_G_F = gradient_F(P)
    gradient_norm = np.zeros_like(P)
    for i in range(0, len(P)-2,2):
        gradient_norm[i] = 𝜆*(P[i]-D[i])
    gradient_norm[-1] = 𝜆*(P[-1]-D[-1])
    return gradient_norm + gradient_G_F

def GD(P, 𝜆, tol, maxiter):
    D = P
    𝛼 = 0.01  # Step size
    d = gradient_G(D,P,𝜆)
    norm = np.linalg.norm(-d)
    P_new = P + 𝛼*d
    it = 0
    while it < maxiter:
        d_new = -gradient_G(D, P_new,𝜆)
        P_new += 𝛼 * d_new
        norm = np.linalg.norm(-d_new)
        it += 1
    return P_new, it
      
print(compress_P(P))
print(gradient_F(P))
print(gradient_G(np.copy(P),P,2))

print(GD(P, 2, 3, 50))
print(GD(P, 2, 3, 100000))



[[-1.          0.        ]
 [-1.          0.33333333]
 [ 1.          0.        ]
 [ 1.         -0.33333333]
 [ 0.33333333 -1.        ]
 [ 0.         -1.        ]]
[[ 12.   0.]
 [-24. -12.]
 [  0. -12.]
 [-12.  24.]
 [-12.   0.]
 [ 24.  12.]
 [-12. -24.]
 [  0.  12.]]
[[ 12.   0.]
 [-24. -12.]
 [  0. -12.]
 [-12.  24.]
 [-12.   0.]
 [ 24.  12.]
 [-12. -24.]
 [  0.  12.]]
(array([[ 0.58065569,  1.52921016],
       [ 1.06022342,  1.45372845],
       [ 1.53018607,  1.02683002],
       [ 1.47205427,  0.67326451],
       [ 1.07208621, -0.03041954],
       [ 0.72642495, -0.37896773],
       [ 0.37896773, -0.72642495],
       [ 0.03041954, -1.07208621]]), 50)
(array([[ 1.06250000e+00,  1.50000000e+00],
       [ 1.32291667e+00,  1.41666667e+00],
       [ 1.50000000e+00,  1.00000000e+00],
       [ 1.41666667e+00,  6.66666667e-01],
       [ 1.00000000e+00, -1.15729754e-15],
       [ 6.66666667e-01, -3.33333333e-01],
       [ 3.33333333e-01, -6.66666667e-01],
       [ 2.15212463e-15, -1.00000000e+

In [2]:

# # Returns value of second term
# def F(P):
#     n = len(P)
#     sum_1 = 0
#     sum_2 = 0
#     for i in range(2, n - 2, 2):
#         sum_1 += 6 * (P[i + 1] - P[i])
#         sum_2 += 3 * (P[i] - P[i + 1])
#     return 36 * (norm(-P[0] + 3 * P[1] + sum_1 - 3 * P[-2] + P[-1]) ** 2 + norm(P[0] - 2 * P[1] + sum_2 + P[-2]) ** 2)

# #Returns value of G
# def G(P, 𝜆):
#     #Norm of all the elements to p_{1,m-1}
#     sum_norm = 0
#     for i in range(0, int(len(P) // 2 - 1)):
#         for j in range(len(P)):
#             if i <= j < 2 * i:
#                 sum_norm += norm(P[j] - P[i*2]) ** 2
                
#     #Adding the norm of the last elements
#     sum_norm += norm(P[-4] - P[-1])**2 + norm(P[-3] - P[-1])**2 + norm(P[-2] - P[-1])**2
#     return (𝜆 / 2) * sum_norm + F(P)

# def gradient_G(P,𝜆): 
#     d = np.zeros_like(P)
#     P_plus_h = P.copy()
#     h = 0.1
#     for i in range(len(P)):
#         for j in range(len(P[i])):
#             P_plus_h[i][j] += h
#             d[i][j] = (G(P_plus_h, 𝜆) - G(P, 𝜆))/ h  #Calculate appriximate gradient
#     return d

# #  Calculates the gradient descent for our points P
# 




# result, iterations = GD(P, 𝜆=2, tol=1, maxiter = 6)
# print("Result:", result)
# print("Iterations:", iterations)
        